export const RANKING_TABLE_COLUMNS = [
  {
    name: 'Stt',
    mappingField: 'index',
    variant: '-index',
    format: 'number',
    icon: '',
    unit: '',
  },
  {
    name: 'Tên',
    mappingField: 'name',
    variant: '-name',
    format: 'text',
    icon: '',
    unit: '',
  },
  {
    name: 'Giá',
    mappingField: 'price',
    variant: '-sublease-achievement-rate',
    format: 'integer',
    icon: '',
    unit: 'VND',
  },
  {
    name: 'Image',
    mappingField: 'img',
    variant: '-image',
    icon: '',
    unit: '',
  },
  {
    name: 'Mô tả',
    mappingField: 'description',
    variant: '-position-name',
    format: 'text',
    isSortable: false,
    icon: '',
    unit: '',
  },
  {
    name: 'OS',
    mappingField: 'os',
    variant: '-achievement-rate',
    format: 'text',
    isSortable: true,

    unit: '%',
  },
  {
    name: 'Màu',
    mappingField: 'color',
    variant: '-sublease-achievement-rate',
    format: 'text',
    isSortable: true,
    unit: '%',
  },
  {
    name: 'Ram',
    mappingField: 'ram',
    variant: '-rate-fee',
    format: 'integer',
    unit: 'GB',
  },
]
