export const TABLE_COLUMNS = [
  {
    name: 'Stt',
    mappingField: 'index',
    variant: '-index',
    format: 'number',
    icon: '',
    unit: '',
  },
  {
    name: 'Tên',
    mappingField: 'name',
    variant: '-name',
    format: 'text',
    icon: '',
    unit: '',
  },
  {
    name: 'Giá',
    mappingField: 'price',
    variant: '-price',
    format: 'integer',
    icon: '',
    unit: 'VND',
  },
  {
    name: 'Image',
    mappingField: 'img',
    variant: '-image',
    icon: '',
    unit: '',
  },
  {
    name: 'Hãng sản xuất',
    mappingField: 'model',
    variant: '-model',
    format: 'text',
    isSortable: true,

    unit: '%',
  },
  {
    name: 'Màu',
    mappingField: 'color',
    variant: '-color',
    format: 'text',
    isSortable: true,
    unit: '%',
  },
  {
    name: 'Ram',
    mappingField: 'ram',
    variant: '-rate-fee',
    format: 'integer',
    unit: 'GB',
  },
]
